<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" encoding="UTF-8"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap Index</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background: #fff;
            color: #222;
            margin: 0;
            padding: 0;
          }
          .sitemap-container {
            max-width: 790px;
            margin: 40px auto 0 auto;
            background: #fff;
            box-shadow: 0 2px 16px rgba(0,0,0,0.07);
            border-radius: 10px;
            padding: 32px 24px 24px 24px;
          }
          h1 {
            color: #333;
            text-align: center;
            margin-bottom: 10px;
          }
          p {
            text-align: center;
            margin-bottom: 24px;
            color: #555;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin: 0 auto;
            background: #fafbfc;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 1px 4px rgba(0,0,0,0.03);
          }
          th, td {
            border: 1px solid #e0e0e0;
            padding: 10px 16px;
            text-align: left;
            font-size: 14px;
          }
          th {
            background: #f5f5f5;
            font-weight: 600;
            text-align: left;
          }
          tr:nth-child(even) {
            background: #f9f9f9;
          }
          a {
            color: #0073aa;
            text-decoration: none;
            word-break: break-all;
          }
          a:hover {
            text-decoration: underline;
          }
        </style>
      </head>
      <body>
        <div class="sitemap-container">
          <h1>XML Sitemap</h1>
          <p>Generated by your Blog Management System. This is an XML Sitemap Index, meant for consumption by search engines.</p>
          <table>
            <tr>
              <th>Sitemap</th>
              <th>Last Modified</th>
            </tr>
            <xsl:for-each select="sm:sitemapindex/sm:sitemap">
              <tr>
                <td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
                <td><xsl:value-of select="sm:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
