<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">

  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>XML Sitemap</title>
        <style type="text/css">
          body { font-family: Arial, Helvetica, sans-serif; background:#fff; color:#111; margin:0; }
          .wrap { max-width: 780px; margin: 0 auto; padding: 48px 18px; }
          .card { border:1px solid #e6e6e6; border-radius: 10px; box-shadow: 0 6px 24px rgba(0,0,0,.06); overflow:hidden; }
          h1 { text-align:center; margin:0 0 10px 0; font-size: 36px; font-weight:700; }
          .sub { text-align:center; margin:0 0 22px 0; color:#666; font-size: 13px; }
          table { width:100%; border-collapse: collapse; }
          thead th { background:#f5f6f7; text-align:left; font-size: 13px; padding: 12px 14px; border-bottom:1px solid #e6e6e6; }
          tbody td { padding: 12px 14px; border-bottom:1px solid #eee; font-size: 13px; vertical-align: top; }
          tbody tr:last-child td { border-bottom: 0; }
          a { color:#1a73e8; text-decoration:none; }
          a:hover { text-decoration:underline; }
          .muted { color:#666; }
        </style>
      </head>
      <body>
        <div class="wrap">
          <h1>XML Sitemap</h1>
          <p class="sub">
            Generated by your Blog Management System. This is an XML Sitemap Index, meant for consumption by search engines.
          </p>

          <div class="card">
            <table>
              <thead>
                <tr>
                  <th style="width:70%;">Sitemap</th>
                  <th style="width:30%;">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="s:sitemapindex/s:sitemap">
                  <tr>
                    <td>
                      <a>
                        <xsl:attribute name="href">
                          <xsl:value-of select="s:loc"/>
                        </xsl:attribute>
                        <xsl:value-of select="s:loc"/>
                      </a>
                    </td>
                    <td class="muted">
                      <xsl:value-of select="s:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>

</xsl:stylesheet>

